### ISSUE TITLE
Bug Report related to OpenFilter and AAC AD

### ISSUE THREAD

**Issue by itsTyrion** [UnnamedCheese/OpenFilter#1]
Using OpenFilter causes AAC AdditionPro to spam the console and log with errors, removing OpenFilter fixes the bug again. I posted the log on pastebin, so you can take a look at it: https://pastebin.com/dsDv2C4W

**Comment by Porama6400** [comment]
Sorry for late reply, I've been busy recently

Please provide these information.

OpenFilter version.
AACAdditionPro version.
Server version.

**Comment by BlackHawk2306** [comment]
Openfilter version: latest (2.3.2)
AACAdditionPro version: latest (3.4.2)
Server version: Spigot 1.8

**Comment by Porama6400** [comment]
I can't figure it out yet

I have no idea what 
**at de.photon.AACAdditionPro.z.lambda$subEnable$0(z.java) ~[?:?]**
is
